### ISSUE TITLE
Error loading registry data

### ISSUE THREAD

**Issue by stovan12** [syldium/worldgen#15]
Using custom noise gives errors

>.... [18:09:48 ERROR]: Encountered an unexpected exception
com.google.gson.JsonParseException: Error loading registry data: No key ore_veins_enabled in MapLike[{"aquifers_enabled":false,"noodle_caves_enabled":false,"deepslate_enabled":true,"bedrock_floor_position":0,"sea_level":63,"disable_mob_generation":false,"default_block":{"Name":"minecraft:deepslate","Properties":{"axis":"y"}},"default_fluid":{"Properties":{"level":"0"},"Name":"minecraft:water"},"bedrock_roof_position":-2147483648,"structures":{"structures":{"minecraft:ocean_ruin":{"spacing":20,"separation":8,"salt":14357621},"minecraft:endcity":{"spacing":20,"separation":11,"salt":10387313},"minecraft:jungle_pyramid":{"spacing":32,"separation":8,"salt":14357619},"minecraft:bastion_remnant":{"spacing":27,"separation":4,"salt":30084232},"minecraft:fortress":{"spacing":27,"separation":4,"salt":30084232},"minecraft:mansion":{"spacing":80,"separation":20,"salt":10387319},"minecraft:stronghold":{"spacing":1,"separation":0,"salt":0},"minecraft:buried_treasure":{"spacing":1,"separation":0,"salt":0},"minecraft:village":{"spacing":32,"separation":8,"salt":10387312},"minecraft:monument":{"spacing":32,"separation":5,"salt":10387313},"minecraft:ruined_portal":{"spacing":40,"separation":15,"salt":34222645},"minecraft:swamp_hut":{"spacing":32,"separation":8,"salt":14357620},"minecraft:nether_fossil":{"spacing":2,"separation":1,"salt":14357921},"minecraft:shipwreck":{"spacing":24,"separation":4,"salt":165745295},"minecraft:mineshaft":{"spacing":1,"separation":0,"salt":0},"minecraft:pillager_outpost":{"spacing":32,"separation":8,"salt":165745296},"minecraft:desert_pyramid":{"spacing":32,"separation":8,"salt":14357617},"minecraft:igloo":{"spacing":32,"separation":8,"salt":14357618}}},"noise":{"simplex_surface_noise":true,"random_density_offset":true,"size_vertical":2,"density_factor":1,"density_offset":-0.46875,"top_slide":{"target":-10,"size":3,"offset":0},"bottom_slide":{"target":15,"size":3,"offset":0},"size_horizontal":1,"min_y":0,"height":256,"sampling":{"xz_scale":0.9999999814507745,"y_scale":0.9999999814507745,"xz_factor":80,"y_factor":160}}}]; No key noise_caves_enabled in MapLike[{"aquifers_enabled":false,"noodle_caves_enabled":false,"deepslate_enabled":true,"bedrock_floor_position":0,"sea_level":63,"disable_mob_generation":false,"default_block":{"Name":"minecraft:deepslate","Properties":{"axis":"y"}},"default_fluid":{"Properties":{"level":"0"},"Name":"minecraft:water"},"bedrock_roof_position":-2147483648,"structures":{"structures":{"minecraft:ocean_ruin":{"spacing":20,"separation":8,"salt":14357621},"minecraft:endcity":{"spacing":20,"separation":11,"salt":10387313},"minecraft:jungle_pyramid":{"spacing":32,"separation":8,"salt":14357619},"minecraft:bastion_remnant":{"spacing":27,"separation":4,"salt":30084232},"minecraft:fortress":{"spacing":27,"separation":4,"salt":30084232},"minecraft:mansion":{"spacing":80,"separation":20,"salt":10387319},"minecraft:stronghold":{"spacing":1,"separation":0,"salt":0},"minecraft:buried_treasure":{"spacing":1,"separation":0,"salt":0},"minecraft:village":{"spacing":32,"separation":8,"salt":10387312},"minecraft:monument":{"spacing":32,"separation":5,"salt":10387313},"minecraft:ruined_portal":{"spacing":40,"separation":15,"salt":34222645},"minecraft:swamp_hut":{"spacing":32,"separation":8,"salt":14357620},"minecraft:nether_fossil":{"spacing":2,"separation":1,"salt":14357921},"minecraft:shipwreck":{"spacing":24,"separation":4,"salt":165745295},"minecraft:mineshaft":{"spacing":1,"separation":0,"salt":0},"minecraft:pillager_outpost":{"spacing":32,"separation":8,"salt":165745296},"minecraft:desert_pyramid":{"spacing":32,"separation":8,"salt":14357617},"minecraft:igloo":{"spacing":32,"separation":8,"salt":14357618}}},"noise":{"simplex_surface_noise":true,"random_density_offset":true,"size_vertical":2,"density_factor":1,"density_offset":-0.46875,"top_slide":{"target":-10,"size":3,"offset":0},"bottom_slide":{"target":15,"size":3,"offset":0},"size_horizontal":1,"min_y":0,"height":256,"sampling":{"xz_scale":0.9999999814507745,"y_scale":0.9999999814507745,"xz_factor":80,"y_factor":160}}}]; No key min_surface_level in MapLike[{"aquifers_enabled":false,"noodle_caves_enabled":false,"deepslate_enabled":true,"bedrock_floor_position":0,"sea_level":63,"disable_mob_generation":false,"default_block":{"Name":"minecraft:deepslate","Properties":{"axis":"y"}},"default_fluid":{"Properties":{"level":"0"},"Name":"minecraft:water"},"bedrock_roof_position":-2147483648,"structures":{"structures":{"minecraft:ocean_ruin":{"spacing":20,"separation":8,"salt":14357621},"minecraft:endcity":{"spacing":20,"separation":11,"salt":10387313},"minecraft:jungle_pyramid":{"spacing":32,"separation":8,"salt":14357619},"minecraft:bastion_remnant":{"spacing":27,"separation":4,"salt":30084232},"minecraft:fortress":{"spacing":27,"separation":4,"salt":30084232},"minecraft:mansion":{"spacing":80,"separation":20,"salt":10387319},"minecraft:stronghold":{"spacing":1,"separation":0,"salt":0},"minecraft:buried_treasure":{"spacing":1,"separation":0,"salt":0},"minecraft:village":{"spacing":32,"separation":8,"salt":10387312},"minecraft:monument":{"spacing":32,"separation":5,"salt":10387313},"minecraft:ruined_portal":{"spacing":40,"separation":15,"salt":34222645},"minecraft:swamp_hut":{"spacing":32,"separation":8,"salt":14357620},"minecraft:nether_fossil":{"spacing":2,"separation":1,"salt":14357921},"minecraft:shipwreck":{"spacing":24,"separation":4,"salt":165745295},"minecraft:mineshaft":{"spacing":1,"separation":0,"salt":0},"minecraft:pillager_outpost":{"spacing":32,"separation":8,"salt":165745296},"minecraft:desert_pyramid":{"spacing":32,"separation":8,"salt":14357617},"minecraft:igloo":{"spacing":32,"separation":8,"salt":14357618}}},"noise":{"simplex_surface_noise":true,"random_density_offset":true,"size_vertical":2,"density_factor":1,"density_offset":-0.46875,"top_slide":{"target":-10,"size":3,"offset":0},"bottom_slide":{"target":15,"size":3,"offset":0},"size_horizontal":1,"min_y":0,"height":256,"sampling":{"xz_scale":0.9999999814507745,"y_scale":0.9999999814507745,"xz_factor":80,"y_factor":160}}}]
at net.minecraft.core.RegistryAccess.lambda$readRegistry$6(RegistryAccess.java:221) ~[app:?]
at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
at net.minecraft.core.RegistryAccess.a(RegistryAccess.java:221) ~[app:?]
at net.minecraft.core.RegistryAccess.load(RegistryAccess.java:212) ~[app:?]
at net.minecraft.resources.RegistryReadOps.createAndLoad(RegistryReadOps.java:57) ~[patched_1.17.1.jar:git-Paper-295]
at net.minecraft.resources.RegistryReadOps.createAndLoad(RegistryReadOps.java:51) ~[patched_1.17.1.jar:git-Paper-295]
at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:527) ~[patched_1.17.1.jar:git-Paper-295]

**Comment by stovan12** [comment]
version is 1.17.1 paper
